### PR TITLE
Add double builds

### PR DESCRIPTION
**Pull request by Ughuuu**
- Fixes https://github.com/libriscv/godot-sandbox/issues/75#issuecomment-2338994998

### CODE REVIEW

**Comment by Ughuuu** [comment]
This will basically double the build time though. Also possibly the export size. But it will work either if you export single or double, so thats nice.

**Comment by fire** [comment]
Are the windows versions builders flip flopping between newer and older machines?

**Comment by Ughuuu** [comment]
Problem seems to be building single then double. We need to build them in parallel to start from fresh/clean step.

**Comment by fire** [comment]
Thanks

**Pull request merged**
