### PR TITLE
Move rust sys calls to new repo

### PR DESCRIPTION
**Pull request by Ughuuu**

### CODE REVIEW

**Comment by fire** [comment]
@Ughuuu There are some conflicts.

**Comment by fwsGonzo** [comment]
I don't mind changing my workflow - just wanted something that had working Github Actions before completing the move.

**Comment by fire** [comment]
Can I close the pull request if we're not thinking of merging it in the near future? It's ok to merge too!

**Comment by Ughuuu** [comment]
Sure, let's wait then until the api stabilizes a bit and then we can move everything to the new repo.

**Pull request closed without merging**
