### PR TITLE
Rework Variant to allow storing complex variants, treat String as complex

### PR DESCRIPTION
**Pull request by fwsGonzo**
This lowers latency greatly when using strings, and simplifies other language implementations
```
GDScript call 6xargs overhead: 96 nanos
Sandbox vmcall 6xargs overhead: 98 nanos
```
The above micro-benchmark is calling a function with 6 string arguments, with GDScript and then the sandbox

### CODE REVIEW

**Comment by fire** [comment]
Do you need testing? Or we can release and test.

Does the test project need an update?

**Comment by fwsGonzo** [comment]
I think this PR is done now - but we need to test it a bit since this is a big change.

And then we can release, yes. This changes the containers too, but it's an important change that drastically lowers latency across the board and paves the way for other types to be supported more easily.

**Comment by fire** [comment]
Is there a way to update the build containers without breaking production?

**Comment by fwsGonzo** [comment]
In this case, sadly not. But I suspect in the future the API will mostly be appended to, so it's less of a problem

**Comment by fire** [comment]
An idea came to me. Have a flag or a project setting that we can toggle for using a separate set of docker containers for pre-release.

**Pull request merged**
